task_name: customer_analytics
namespace: data_pipeline
version: "2.6.0"
description: "Resilient customer analytics pipeline with parallel processing"

# Enterprise annotations for monitoring
annotations:
  team: "data-engineering"
  criticality: "high"
  sla_hours: 8
  dependencies: ["postgresql", "redis", "crm_api"]

# Parallel data extraction phase
step_templates:
  - name: extract_orders
    description: "Extract order data from transactional database"
    handler_class: "DataPipeline::StepHandlers::ExtractOrdersHandler"
    timeout_seconds: 1800  # 30 minutes
    max_retries: 3
    retry_backoff: exponential

  - name: extract_users
    description: "Extract user data from CRM system"
    handler_class: "DataPipeline::StepHandlers::ExtractUsersHandler"
    timeout_seconds: 1200  # 20 minutes - CRM can be flaky
    max_retries: 5
    retry_backoff: exponential

  - name: extract_products
    description: "Extract product data from inventory system"
    handler_class: "DataPipeline::StepHandlers::ExtractProductsHandler"
    timeout_seconds: 900   # 15 minutes
    max_retries: 3
    retry_backoff: exponential

  # Dependent transformations (wait for all extractions)
  - name: transform_customer_metrics
    description: "Calculate customer behavior metrics"
    handler_class: "DataPipeline::StepHandlers::TransformCustomerMetricsHandler"
    depends_on: ["extract_orders", "extract_users"]
    timeout_seconds: 2700  # 45 minutes
    max_retries: 2

  - name: transform_product_metrics
    description: "Calculate product performance metrics"
    handler_class: "DataPipeline::StepHandlers::TransformProductMetricsHandler"
    depends_on: ["extract_orders", "extract_products"]
    timeout_seconds: 1800  # 30 minutes
    max_retries: 2

  # Final aggregation and output
  - name: generate_insights
    description: "Generate business insights and recommendations"
    handler_class: "DataPipeline::StepHandlers::GenerateInsightsHandler"
    depends_on: ["transform_customer_metrics", "transform_product_metrics"]
    timeout_seconds: 1200  # 20 minutes

  - name: update_dashboard
    description: "Update executive dashboard with new metrics"
    handler_class: "DataPipeline::StepHandlers::UpdateDashboardHandler"
    depends_on: ["generate_insights"]
    max_retries: 3
    retry_backoff: exponential

  - name: send_notifications
    description: "Send completion notifications to stakeholders"
    handler_class: "DataPipeline::StepHandlers::SendNotificationsHandler"
    depends_on: ["update_dashboard"]
    max_retries: 5
    retry_backoff: exponential

# Custom events for this pipeline
custom_events:
  - name: "data_extraction_started"
    description: "Fired when any extraction step begins"
  - name: "data_extraction_completed"
    description: "Fired when extraction step completes with metrics"
  - name: "pipeline_milestone_reached"
    description: "Fired at key pipeline milestones"
