#!/usr/bin/env bash
# =============================================================================
# Generate the Generated Reference index page
# =============================================================================
#
# Writes src/generated/index.md as a landing page for all generated content.
# This runs after sync (which may overwrite index.md) and after other
# generators (which create the diagram files).
#
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUTPUT="${REPO_ROOT}/src/generated/index.md"

echo "Generating index page..."

mkdir -p "$(dirname "${OUTPUT}")"

cat > "${OUTPUT}" <<'EOF'
# Generated Reference

This section contains documentation generated from static analysis of the Tasker source code
and comprehensive configuration reference from `tasker-ctl docs`. These artifacts are kept
in sync with the codebase via the `cargo make generate` pipeline.

---

## Architecture Diagrams

Visual representations of system structure generated from source analysis.

- **[Crate Dependency Graph](crate-dependency-graph.md)** — Mermaid flowchart showing inter-crate
  dependencies across the tasker-core workspace, organized by Core Libraries, Services, and FFI Workers.

- **[State Machine Diagrams](state-machine-diagrams.md)** — Mermaid state diagrams for the Task
  (12-state) and Workflow Step (10-state) lifecycle state machines, extracted from Rust source.

## Database Schema

- **[Database Schema](database-schema.md)** — Mermaid ER diagram showing all tables, columns,
  and foreign key relationships in the Tasker PostgreSQL database.

## Configuration Reference

Comprehensive reference for all 246 Tasker configuration parameters, generated by `tasker-ctl docs`.

- **[Common Configuration](config-reference-common.md)** — Shared settings (backoff, cache, circuit breakers, database, queues)
- **[Orchestration Configuration](config-reference-orchestration.md)** — Orchestration-specific settings (batch processing, DLQ, gRPC, web)
- **[Worker Configuration](config-reference-worker.md)** — Worker-specific settings (circuit breakers, event systems, FFI dispatch)
- **[Complete Reference](config-reference-complete.md)** — All parameters in a single page

## LLM-Powered Guides

These guides are generated with optional local LLM support (Ollama) for richer operational context.
Run `cargo make generate-all` to generate these alongside the standard artifacts.

- **[Configuration Operational Guide](config-operational-guide.md)** — Tuning advice for key parameters:
  when to adjust values, recommended settings by deployment size, and common pitfalls.

- **[Error Troubleshooting Guide](error-troubleshooting-guide.md)** — Diagnosis and resolution steps
  for Tasker error types: what causes each error, how to diagnose, and how to fix.

- **[ADR Summary](adr-summary.md)** — Summary table of Architectural Decision Records with
  AI-generated overviews of each decision.

---

*Generated artifacts are produced by scripts in `cargo-make/scripts/generate-*.sh` and committed to the repository.*
*Regenerate with: `cargo make generate` (deterministic) or `cargo make generate-all` (includes LLM-powered)*
EOF

echo "  Output: ${OUTPUT}"
echo "Generated reference index page written."
